### ISSUE TITLE
Default accessiblity should be kSecAttrAccessibleWhenUnlockedThisDeviceOnly

### ISSUE THREAD

**Issue by fproulx-pbox** [auth0/SimpleKeychain#17]
Right now accessibility is kSecAttrAccessibleAfterFirstUnlock which basically means always available even when device locked is and has not been rebooted recently....

A more sensible default should be kSecAttrAccessibleWhenUnlockedThisDeviceOnly otherwise it's easy for a programmer to leave the default assume it's protected well.

**Comment by hzalaz** [comment]
@fproulx-pbox I agree its not the most secure default, setting to `kSecAttrAccessibleWhenUnlockedThisDeviceOnly` will cause some trouble to people using background tasks or relying on iCloud backups but since that is not that common might be a good idea to change it.
Fell free to submit a PR if you want.
