### ISSUE TITLE
Keychain value do not removing after app was uninstalled

### ISSUE THREAD

**Issue by dimariouz** [auth0/SimpleKeychain#72]

**Comment by nstublen** [comment]
SimpleKeychain won't be able to resolve this behavior since it is part of iOS. You can read about it here: https://forums.developer.apple.com/thread/36442.

I am not aware of any updates to this behavior on iOS since that thread, which has some suggestions on how to force your app to lose access to the keychain values if that's helpful.

**Comment by cocojoe** [comment]
Thanks for the response @nstublen, agreed.
